training:
    optim:
        lr: 4e-3
        weight_decay: 1e-6
        max_lr: 3e-3
        start_lr: 8e-4
        end_lr: 8e-4
        pct_start: 0.2

    max_steps: 100000

logging:
    log_val_medias_every_n_epochs: 20
    log_train_medias_every_n_epochs: 20
    filter_images:
#        - pred_trans_attr_to_attr
#        - pred_trans_act_to_act
#        - pred_trans_v_latents_to_v_latents
        - pred_trans_attr_to_v_latents
#        - pred_trans_attr_to_act
        - pred_trans_act_to_v_latents
#        - pred_trans_act_to_attr
#        - pred_trans_v_latents_to_attr
#        - pred_trans_v_latents_to_act
#        - pred_cycle_v_latents_to_attr
#        - pred_cycle_v_latents_to_act
#        - pred_cycle_act_to_attr
#        - pred_cycle_act_to_v_latents
#        - pred_cycle_attr_to_v_latents
#        - pred_cycle_attr_to_act
default_root_dir: "~/shimmer-metaworld/"
domains:
    - checkpoint_path: "/mnt/datashare/yelhelw/checkpoints/shimmer-meta-ekh9k4of/epoch=157.ckpt"
      domain_type: v_latents
    - checkpoint_path: "#{default_root_dir}/pretrained/domain_act.ckpt"
      domain_type: act

domain_data_args:
    v_latents:
        presaved_path: vae_v_shimmer.npy
    attr:
        n_unpaired: 0

domain_proportions: 
    -   domains: ["attr"]
        proportion: 1.0
    -   domains: ["v_latents"]
        proportion: 1.0
    -   domains: ["v", "attr"]
        proportion: 1.0
    -   domains: ["v", "attr","act"]
        proportion: 1.0

visualization:
    explore_vae:
        wandb_name: 0u5us4g7
        checkpoint: shimmer-meta-0u5us4g7/epoch=156.ckpt
    explore_gw:
        # wandb_name: zdufxid0
        checkpoint: shimmer-meta-cpcjzmp8/epoch=147.ckpt
        domain: v_latents