domain_modules:
    visual:
        num_channels : 3
training:
    optim:
        lr: 5e-3
        max_lr: 3e-3
        weight_decay: 1e-5

    batch_size : 128
    num_workers : 8
    max_steps: 100_000


logging:
    log_val_medias_every_n_epochs: 10
    log_train_medias_every_n_epochs: 10
